# Generated by Django 4.0.3 on 2022-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mail_id', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=10)),
                ('School_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
