# Generated by Django 4.0.3 on 2022-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_loggedinperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffnmae', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('workexperience', models.IntegerField()),
                ('schoolname', models.CharField(max_length=100)),
                ('roles', models.CharField(max_length=100)),
                ('responsibilities', models.CharField(max_length=10000)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=1000)),
                ('joiningdate', models.DateField()),
            ],
        ),
    ]
