# Generated by Django 4.0.3 on 2022-03-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_staffdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='staffnmae',
            new_name='staffname',
        ),
    ]
