# Generated by Django 4.0.3 on 2022-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_staffdetails_responsibilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='std1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
            ],
        ),
    ]
