# Generated by Django 4.0.3 on 2022-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_std1'),
    ]

    operations = [
        migrations.AddField(
            model_name='std1',
            name='school_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='schoolname',
            field=models.CharField(max_length=500),
        ),
    ]
