# Generated by Django 4.0.3 on 2022-03-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_std2'),
    ]

    operations = [
        migrations.CreateModel(
            name='std10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='std9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=500)),
            ],
        ),
    ]
