# Generated by Django 4.0.3 on 2022-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_cstduse'),
    ]

    operations = [
        migrations.CreateModel(
            name='stafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('staffname', models.CharField(max_length=50)),
            ],
        ),
    ]
