# Generated by Django 4.0.3 on 2022-03-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_stafftimetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftimetable',
            old_name='day',
            new_name='Monday_period',
        ),
        migrations.RemoveField(
            model_name='stafftimetable',
            name='period',
        ),
    ]
