# Generated by Django 4.0.3 on 2022-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_day_stafftimetable_monday_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mondaystafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('monday1', models.CharField(max_length=20)),
                ('monday2', models.CharField(max_length=20)),
                ('monday3', models.CharField(max_length=20)),
                ('monday4', models.CharField(max_length=20)),
                ('monday5', models.CharField(max_length=20)),
                ('monday6', models.CharField(max_length=20)),
                ('monday7', models.CharField(max_length=20)),
                ('monday8', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='stafftimetable',
        ),
    ]
