# Generated by Django 4.0.3 on 2022-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_mondaystafftimetable_delete_stafftimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mondaystafftimetable',
            name='schoolname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
