# Generated by Django 4.0.3 on 2022-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_mondaystafftimetable_schoolname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
