# Generated by Django 4.0.3 on 2022-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_ssprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='fridaystafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('friday1', models.CharField(max_length=20)),
                ('friday2', models.CharField(max_length=20)),
                ('friday3', models.CharField(max_length=20)),
                ('friday4', models.CharField(max_length=20)),
                ('friday5', models.CharField(max_length=20)),
                ('friday6', models.CharField(max_length=20)),
                ('friday7', models.CharField(max_length=20)),
                ('friday8', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='saturdaystafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('saturday1', models.CharField(max_length=20)),
                ('saturday2', models.CharField(max_length=20)),
                ('saturday3', models.CharField(max_length=20)),
                ('saturday4', models.CharField(max_length=20)),
                ('saturday5', models.CharField(max_length=20)),
                ('saturday6', models.CharField(max_length=20)),
                ('saturday7', models.CharField(max_length=20)),
                ('saturday8', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='thursdaystafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('thursday1', models.CharField(max_length=20)),
                ('thursday2', models.CharField(max_length=20)),
                ('thursday3', models.CharField(max_length=20)),
                ('thursday4', models.CharField(max_length=20)),
                ('thursday5', models.CharField(max_length=20)),
                ('thursday6', models.CharField(max_length=20)),
                ('thursday7', models.CharField(max_length=20)),
                ('thursday8', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tuesdaystafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('tuesday1', models.CharField(max_length=20)),
                ('tuesday2', models.CharField(max_length=20)),
                ('tuesday3', models.CharField(max_length=20)),
                ('tuesday4', models.CharField(max_length=20)),
                ('tuesday5', models.CharField(max_length=20)),
                ('tuesday6', models.CharField(max_length=20)),
                ('tuesday7', models.CharField(max_length=20)),
                ('tuesday8', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wednesdaystafftimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('wednesday1', models.CharField(max_length=20)),
                ('wednesday2', models.CharField(max_length=20)),
                ('wednesday3', models.CharField(max_length=20)),
                ('wednesday4', models.CharField(max_length=20)),
                ('wednesday5', models.CharField(max_length=20)),
                ('wednesday6', models.CharField(max_length=20)),
                ('wednesday7', models.CharField(max_length=20)),
                ('wednesday8', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
    ]
