# Generated by Django 4.0.3 on 2022-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_fridaystafftimetable_saturdaystafftimetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cstaffuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstaff', models.CharField(max_length=50)),
            ],
        ),
    ]
