# Generated by Django 4.0.3 on 2022-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_useridpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridpassword',
            name='schoolname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
